<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <title>Welcome!</title>
    <meta charset="utf-8"/>
</head>
<body>
<h1>Login page</h1>

<form method="post" action="usercheck">
    Login:
    <p><input type="text" name="username" placeholder="input login">
    <p></p>Password:
    <p><input type="password" name="password" placeholder="input password">
    <p>

    <input type="submit">
</form>

<img src="image/776754.png" alt="">

<p>
</body>
</html>