# create new car
POST http://localhost:8080/cars
Content-Type: application/json

{
"model": "Xianss",
"number": "43FBSIFNRE"
}

###
GET http://localhost:8080/cars/1

###


###
DELETE http://localhost:8080/cars/5